WITH DATE_DIMENSION AS (
    SELECT * FROM {{ ref('dates') }}
)

SELECT
    DATE_DAY,
    DAY_OF_WEEK,
    DAY_OF_MONTH,
    DAY_OF_YEAR,
    WEEK_OF_YEAR,
    MONTH_OF_YEAR,
    MONTH_NAME,
    QUARTER_OF_YEAR,
    YEAR_NUMBER
FROM
    DATE_DIMENSION
