SELECT
    ORDERDETAILS.ORDERNUMBER AS ORDER_NUMBER,
    ORDERDETAILS.ORDERLINENUMBER AS ORDER_LINE_NUMBER,
    PRODUCTS.PRODUCTNAME AS PRODUCT_NAME,
    PRODUCTS.PRODUCTSCALE AS PRODUCT_SCALE,
    PRODUCTS.PRODUCTVENDOR AS PRODUCT_VENDOR,
    PRODUCTS.PRODUCTDESCRIPTION AS PRODUCT_DESCRIPTION,
    PRODUCTS.BUYPRICE AS PRODUCT_BUY_PRICE,
    PRODUCTS.MSRP AS PRODUCT_MSRP,
    PRODUCTLINES.TEXTDESCRIPTION AS PRODUCT_LINE,
    ORDERDETAILS.QUANTITYORDERED AS QUANTITY_ORDERED,
    ORDERDETAILS.PRICEEACH AS PRODUCT_PRICE,
    ORDERS.ORDERDATE AS ORDER_DATE,
    ORDERS.REQUIREDDATE AS ORDER_REQUIRED_DATE,
    ORDERS.SHIPPEDDATE AS ORDER_SHIPPED_DATE,
    CUSTOMERS.CUSTOMERNAME AS CUSTOMER_NAME,
    CUSTOMERS.CITY AS CUSTOMER_CITY,
    CUSTOMERS.STATE AS CUSTOMER_STATE,
    CUSTOMERS.POSTALCODE AS CUSTOMER_POSTAL_CODE,
    CUSTOMERS.CREDITLIMIT AS CUSTOMER_CREDIT_LIMIT,
    EMPLOYEES.FIRSTNAME AS SALES_REP_FIRST_NAME,
    EMPLOYEES.LASTNAME AS SALES_REP_LAST_NAME,
    EMPLOYEES.JOBTITLE AS SALES_REP_TITLE,
    ORDERS.STATUS AS ORDER_STATUS,
    ORDERS.COMMENTS AS ORDER_COMMENTS
FROM {{ var("source_schema") }}.ORDERDETAILS
INNER JOIN {{ var("source_schema") }}.ORDERS
    ON ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER
INNER JOIN {{ var("source_schema") }}.PRODUCTS
    ON ORDERDETAILS.PRODUCTCODE = PRODUCTS.PRODUCTCODE
INNER JOIN {{ var("source_schema") }}.PRODUCTLINES
    ON PRODUCTS.PRODUCTLINE = PRODUCTLINES.PRODUCTLINE
INNER JOIN {{ var("source_schema") }}.CUSTOMERS
    ON ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER
INNER JOIN {{ var("source_schema") }}.EMPLOYEES
    ON CUSTOMERS.SALESREPEMPLOYEENUMBER = EMPLOYEES.EMPLOYEENUMBER
